spring:
  application:
    name: audit-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/wallet_db"
    username: wallet
    password: wallet_secret
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    table: audit_flyway_schema_history
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: audit-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.audit.service.TransferEvent
        spring.json.use.type.headers: false

server:
  port: 8081

resilience4j:
  circuitbreaker:
    instances:
      wallet-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 18s
        permitted-number-of-calls-in-half-open-state: 2
        register-health-indicator: true
  retry:
    instances:
      wallet-service:
        max-attempts: 3
        wait-duration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  health:
    circuitbreakers:
      enabled: true

app:
  wallet-service:
    base-url : http://localhost:8080
  kafka:
    topic:
      transfer-events: wallet.transfer.events
